146 rs about us component
tcet-opensource/documentation pull request #162
Opened 2023-06-28 07:07 UTC by preyanskhasingh

[EDITED] Edited the required sections of the code as reviewed according to issue no. #146

2023-06-28 07:27 UTC, himanshu-03 requested changes
Add images and change content as instructed!

2023-06-28 13:05 UTC, preyanskhasingh commented
I have updated the documentation as required as of issue no. #146

2023-06-28 14:40 UTC, himanshu-03 requested changes
Dont just cut short the code already, its hardly  20 lines of code

2023-06-28 14:40 UTC, himanshu-03 commented on docs/projects/resume-screener-website/frontend-components/about-us.mdx
> +### Adding Star Resume Test Option
That is a button not option

2023-06-28 14:42 UTC, himanshu-03 requested changes

2023-06-28 18:14 UTC, preyanskhasingh commented
I have made the required changes on the code as of issue #146

2023-06-29 06:41 UTC, himanshu-03 approved these changes
LGTM!

2023-06-29 06:42 UTC, merged