[ADDED] rs about doc
tcet-opensource/documentation pull request #169
Opened 2023-06-28 15:40 UTC by oldbilldue18

Completed the assigned issue #142

2023-06-28 16:10 UTC, aryadubey03 requested changes
there are several spelling mistakes. Please check properly and do changes.

2023-06-28 16:15 UTC, aryadubey03 requested changes

2023-06-28 16:15 UTC, aryadubey03 commented on docs/projects/resume-screener-website/about-resume-screener-website.mdx
> +<br /><br />
Too much space here

2023-06-28 16:21 UTC, aryadubey03 requested changes
![Screenshot (208)](https://github.com/tcet-opensource/documentation/assets/121982519/e7a8474e-4372-4552-b957-e63c8adfdc3f)

You have left too much space here.

2023-06-28 20:19 UTC, aryadubey03 approved these changes

2023-06-29 06:49 UTC, himanshu-03 approved these changes
LGTM!

2023-06-29 06:49 UTC, merged