230-in-drive-install-in-drive ADDED
tcet-opensource/documentation pull request #307
Opened 2023-10-15 12:59 UTC by oldbilldue18

## Title : tl-install-step-in-drive

## Issue no : #230 

## Description
wrote installation steps of TCET Linux using a bootable drive

2023-10-15 15:15 UTC, vish-rt requested changes
Requested some changes in `installation-in-drive.md` kindly have a look into it. Alongside that, more changes to be done are as follows.

- [ ] Remove the `notes` folder. This is Docusaurus default and not supposed to be on production.
- [ ] Remove `package-lock.json` file from your branch.
- [ ] `package.json` should not have any changes in dependencies. Remove any modifications.

2023-10-15 15:15 UTC, vish-rt commented on docs/projects/tcet-linux/installation/installation-in-drive.md
> +<!-- ![TCET LINUX](/docs/projects/tcet-linux/assets/rufus.png) -->
Broken route has been commented. Apply the fix from line 16 and remove the commented code.

2023-10-15 15:15 UTC, vish-rt commented on docs/projects/tcet-linux/installation/installation-in-drive.md
> +<!-- ![TCET LINUX](/docs/projects/tcet-linux/assets/tldown.png) -->
Broken route has been commented. Review the fix from line 16 and remove this line.

2023-10-15 15:15 UTC, vish-rt commented on docs/projects/tcet-linux/installation/installation-in-drive.md
> +<!-- ![TCET LINUX](/docs/projects/tcet-linux/assets/rufusdown.png) -->
Broken route has been commented. Apply the fix from line 16 and remove the commented code.

2023-10-15 15:15 UTC, vish-rt commented on docs/projects/tcet-linux/installation/installation-in-drive.md
> +<!-- ![TCET LINUX](/docs/projects/tcet-linux/assets/rufusprom.png) -->
Broken route has been commented. Apply the fix from line 16 and remove the commented code.

2023-10-15 15:15 UTC, vish-rt commented on docs/projects/tcet-linux/installation/installation-in-drive.md
> +<!-- ![TCET LINUX](/docs/projects/tcet-linux/assets/rufuspromfinal.png) -->
Broken route has been commented. Apply the fix from line 16 and remove the commented code.

2023-10-15 15:15 UTC, vish-rt commented on docs/projects/tcet-linux/installation/installation-in-drive.md
> +<!-- ![TCET LINUX](/docs/projects/tcet-linux/assets/isofinal.png) -->
Broken route has been commented. Apply the fix from line 16 and remove the commented code.

2023-10-15 15:15 UTC, vish-rt commented on docs/projects/tcet-linux/installation/installation-in-drive.md
> +<!-- ![TCET LINUX](/docs/projects/tcet-linux/assets/rufusdone.png) -->
Broken route has been commented. Apply the fix from line 16 and remove the commented code.

2023-10-15 17:54 UTC, vish-rt requested changes
Changes to be done are as follows.

- [ ] Remove the `notes` folder. This is Docusaurus default and not supposed to be on production.
- [ ] Remove `package-lock.json` file from your branch.
- [ ] `package.json` should not have any changes in dependencies. Remove any modifications.

2023-10-21 09:25 UTC, Akash6222 commented
> Changes to be done are as follows.
> 
> * [ ]  Remove the `notes` folder. This is Docusaurus default and not supposed to be on production.
> * [ ]  Remove `package-lock.json` file from your branch.
> * [ ]  `package.json` should not have any changes in dependencies. Remove any modifications.

@oldbilldue18 plz do the required changes

2023-11-09 17:25 UTC, closed without merging