TMAI August,September,October,November MindBenders Club TCET
tcet-opensource/documentation pull request #364
Opened 2024-01-22 10:22 UTC by AI-ApeX-DeV

2024-01-22 18:35 UTC, demonkillerr approved these changes
LGTM! Should work on image optimization.

2024-01-25 13:42 UTC, vish-rt commented
Changing base to `blogs` as all blog PRs are meant to be made to that branch

2024-01-25 14:04 UTC, vish-rt requested changes
Requesting some minor changes as follows:
1. Utilize [truncate](https://opensource.tcetmumbai.in/blog/blog-posting-guidelines#utilizing-truncate) in all blogs. It reduces the clutter on the blogs page itself and ensures smooth flow. Below is an example of how to truncate your blogs.
![image](https://github.com/tcet-opensource/documentation/assets/93420999/ff8fec13-8663-45d6-90d2-24ce69722082)
2. There's alot of metadata in the frontmatter of each blog, some are not working as intended.
I have added the review comments accordingly on what can be fixed to match with the site theme on the September blog. I recommend adding those fixes in all three blogs.

2024-01-25 14:04 UTC, vish-rt commented on blog/2023-10-17-tmai-september-23/index.md
> +---
Few of the metadata in this frontmatter are not necessary.
Read the [first steps](https://opensource.tcetmumbai.in/blog/blog-posting-guidelines#first-steps) of the posting guidelines for which metadata information should be used.

2024-03-16 06:26 UTC, closed without merging