[FEATURE] Completed Hero Section
tcet-opensource/documentation pull request #53
Opened 2023-04-29 12:30 UTC by adityayadav71

1. Added Hero.js file in src/components/HomePageFeatures/ folder
2. Replaced HomePageHeader component with New Hero component in pages/index.js
3. Added static assets for Hero in static/img/HeroImages
4. Updated tailwind.config.js with necessary extensions like bg image and inner box shadow for "View Projects" Button in Hero

2023-04-29 13:12 UTC, JayeshVP24 requested changes
Majority stuff is great. good work. just make the tiny changes

2023-04-29 13:12 UTC, JayeshVP24 commented on src/components/HomepageFeatures/Hero.js
> +        <p className="px-3 py-1 bg-slate-800 rounded-full z-10 lg:mb-3 mb-6">TCET Open Source</p>
change `py-1` -> `pb-0.5` for more centered appearence
aligning text vertically is a bit of an hassle. this is accepted approach.

also add `text-gray-200`

2023-04-29 13:12 UTC, JayeshVP24 commented on src/components/HomepageFeatures/Hero.js
> +        <button className="flex items-center justify-center gap-x-2 p-2 pl-4 md:mb-0 mb-3 border-b-2 border-indigo-700 shadow-1xl shadow-indigo-400 semibold rounded-full bg-indigo-600">
add `font-semibold`

2023-04-29 13:12 UTC, JayeshVP24 commented on src/components/HomepageFeatures/Hero.js
> +        <button className="flex items-center justify-center gap-x-2 p-2 pl-4 md:mb-0 mb-3 border-b-2 border-indigo-700 shadow-1xl shadow-indigo-400 semibold rounded-full bg-indigo-600">
add a hover effect of some type. up to you!

2023-04-29 13:43 UTC, riyavishwa981 requested changes

2023-04-29 13:43 UTC, riyavishwa981 commented on src/components/HomepageFeatures/Hero.js
> +        <button className="flex items-center justify-center gap-x-2 p-2 pl-4 md:mb-0 mb-3 border-b-2 border-indigo-700 shadow-1xl shadow-indigo-400 semibold rounded-full bg-indigo-600">
add text-white here as well

2023-04-29 13:44 UTC, riyavishwa981 commented
Overall good work and well written code, just make some small changes as mentioned

2023-04-30 14:02 UTC, riyavishwa981 approved these changes

2023-04-30 18:31 UTC, JayeshVP24 approved these changes

2023-04-30 18:32 UTC, merged