[FEATURE] Built Footer Section solve #59
tcet-opensource/documentation pull request #63
Opened 2023-05-01 21:33 UTC by RohanDarade

<img width="424" alt="image" src="https://user-images.githubusercontent.com/72266465/235534965-d283bcc4-d8c9-422e-8a95-0f8602195b61.png">
<img width="753" alt="image" src="https://user-images.githubusercontent.com/72266465/235535027-7a1da8ca-3e4e-4ff4-ac56-c2296409ccc1.png">
<img width="767" alt="image" src="https://user-images.githubusercontent.com/72266465/235535072-e77c02b4-0cd9-4be1-9d9d-d26cd0bf4199.png">
<img width="996" alt="image" src="https://user-images.githubusercontent.com/72266465/235535121-d844022e-900a-4b31-9dc4-0d29a09e939b.png">
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/72266465/235535220-9a974c7a-4732-43de-b95a-21650999cfd6.png">
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/72266465/235535253-6078ed6d-f631-4423-8b1f-e1bdc8319327.png">

2023-05-02 15:41 UTC, riyavishwa981 requested changes

2023-05-02 15:41 UTC, riyavishwa981 commented on src/components/Footer/index.js
> +            TECT Open Source
Make it TCET

2023-05-02 15:41 UTC, riyavishwa981 commented on src/components/Footer/index.js
> +      <div className="flex px-10 pb-12 w-screen flex-col md:flex-row justify-center items-center lg:justify-between flex-wrap">
If you see in the design there is line in between 
![image](https://user-images.githubusercontent.com/79577834/235716011-cf908e8b-47a9-49b4-87fe-04be3ba9f19d.png)

2023-05-02 15:42 UTC, riyavishwa981 commented
Rest everything is good

2023-05-03 18:07 UTC, JayeshVP24 commented
make these changes soon @RohanDarade

2023-05-05 19:00 UTC, JayeshVP24 commented
href links are all incorrect.
make the right changes
youtube https://www.youtube.com/@TCETMumbaiOfficial
find IG, twitter and linkedIn by yourself.

2023-05-06 18:10 UTC, JayeshVP24 approved these changes
LGTM

2023-05-06 18:11 UTC, merged