[UPDATE] Added links in footer
tcet-opensource/documentation pull request #68
Opened 2023-05-06 17:17 UTC by himanshu-03

1. Added Community Links
2. Added Social Media Links
3. Added Currently Ongoing Projects Links

2023-05-06 18:23 UTC, riyavishwa981 approved these changes

2023-05-07 04:55 UTC, vish-rt requested changes
Requesting a minor change before shipping it to main.

2023-05-07 04:55 UTC, vish-rt commented on docusaurus.config.js
> +                to: 'https://t.co/bov6iUrZcB',
Replace the Twitter embed URL with official Discord invite.

2023-05-07 05:02 UTC, himanshu-03 commented on docusaurus.config.js
> +                to: 'https://t.co/bov6iUrZcB',
Twitter Embed URL is redirecting to twitter you want the url to redirect to discord?

2023-05-07 05:11 UTC, vish-rt approved these changes

2023-05-07 14:34 UTC, demonkillerr approved these changes

2023-05-07 14:41 UTC, merged